name: 'Build and publish artifact'
description: 'Build and publish (docker) artifacts'

inputs:
  image-tag:
    description: 'Docker Image Tag'
    required: true
  XIAO_GITHUB_TOKEN:
    description: 'Celobot GitHub token'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'AWS access key id'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secret access key'
    required: true

runs:
  using: composite
  steps:
    - name: Login to Github Container Registry login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: chenxiao-t
        password: ${{ inputs.XIAO_GITHUB_TOKEN }}

#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v4
#      with:
#        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
#        aws-region: eu-central-1
#
#    - name: Login to Amazon ECR
#      id: login-ecr
#      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ../../Dockerfile
        push: true
        tags: ${{ inputs.image-tag }}

    - name: Logout of Amazon ECR
      shell: bash
      if: ${{ always() }}
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
